spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080

spring.boot.admin:
  notify:
    mail:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
