services:
  store:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: store-app
    ports:
      - "8070:8070"  # Expose Kitchen service on host port 8090
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/store  # Kitchen DB inside shared Postgres
      SPRING_DATASOURCE_USERNAME: ajpadilla
      SPRING_DATASOURCE_PASSWORD: Heme19234099
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
    networks:
      - restaurant_shared_network

networks:
  restaurant_shared_network:
    external: true  # shared with Order service
